[package]
name = "bevy_aseprite"
version = "0.1.0"
edition = "2021"
include = ["assets/**/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
serde = "1"
bevy_common_assets = { version = "0.7", features = ["json"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3