[package]
name = "bevy_asepritesheet"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
bevy = "0.11"
serde_json = "1"
serde = "1"